# Generated by Django 6.1.1 on 2026-10-04 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Proje Başlığı')),
                ('slug', models.SlugField(blank=True, max_length=260, unique=True, verbose_name='URL Slug')),
                ('category', models.CharField(choices=[('web', 'Web Geliştirme'), ('mobile', 'Mobil Uygulama'), ('uiux', 'UI / UX Tasarım'), ('ai', 'Yapay Zeka & Veri'), ('devops', 'DevOps & Bulut'), ('opensource', 'Açık Kaynak'), ('game', 'Oyun Geliştirme'), ('other', 'Diğer')], default='web', max_length=30, verbose_name='Kategori')),
                ('description', models.TextField(help_text='Markdown formatı desteklenir. Projenin mimarisi, özellikleri ve kurulum adımlarını detaylandırın.', verbose_name='Proje Açıklaması')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Kapak Görseli')),
                ('demo_url', models.URLField(blank=True, help_text='Örn: https://projem.com', null=True, verbose_name="Canlı Demo URL'i")),
                ('github_url', models.URLField(blank=True, help_text='Örn: https://github.com/kullanici/repo', null=True, verbose_name='GitHub Deposu (Repository)')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Kullanılan Teknolojiler / Etiketler')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Görüntülenme Sayısı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Geliştirici / Yazar')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_projects', to=settings.AUTH_USER_MODEL, verbose_name='Beğeniler')),
            ],
            options={
                'verbose_name': 'Proje',
                'verbose_name_plural': 'Projeler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Yorum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_comments', to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.project', verbose_name='Proje')),
            ],
            options={
                'verbose_name': 'Yorum',
                'verbose_name_plural': 'Yorumlar',
                'ordering': ['created_at'],
            },
        ),
    ]
