# Generated by Django 6.1.1 on 2026-10-04 12:26

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-posta Adresi')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Kullanıcı',
                'verbose_name_plural': 'Kullanıcılar',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Kendinizi, ilgi alanlarınızı ve çalışma hedeflerinizi özetleyin.', max_length=600, verbose_name='Biyografi')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Profil Fotoğrafı')),
                ('specialization', models.CharField(choices=[('frontend', 'Frontend Geliştirici'), ('backend', 'Backend Geliştirici'), ('fullstack', 'Full Stack Geliştirici'), ('mobile', 'Mobil Uygulama Geliştirici'), ('uiux', 'UI/UX Tasarımcı'), ('devops', 'DevOps / Cloud Mühendisi'), ('data_ai', 'Veri Bilimi & Yapay Zeka'), ('other', 'Yazılım & Tasarım Uzmanı')], default='fullstack', max_length=30, verbose_name='Uzmanlık Alanı')),
                ('skills', models.JSONField(blank=True, default=list, help_text="Örnek: ['Python', 'Django', 'Tailwind CSS', 'React']", verbose_name='Yetenekler (Skills)')),
                ('github_url', models.URLField(blank=True, max_length=250, null=True, verbose_name='GitHub Profili')),
                ('linkedin_url', models.URLField(blank=True, max_length=250, null=True, verbose_name='LinkedIn Profili')),
                ('website_url', models.URLField(blank=True, max_length=250, null=True, verbose_name='Kişisel Web Sitesi / Portfolyo')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Konum / Şehir')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kullanıcı Profili',
                'verbose_name_plural': 'Kullanıcı Profilleri',
            },
        ),
    ]
