# Generated by Django 6.1.1 on 2026-10-04 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='İlan Başlığı')),
                ('company_name', models.CharField(max_length=150, verbose_name='Şirket / Kişi Adı')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='jobs/', verbose_name='Şirket Logosu')),
                ('location_type', models.CharField(choices=[('remote', 'Uzaktan (Remote)'), ('hybrid', 'Hibrit (Hybrid)'), ('office', 'Ofis / Yerinde (On-site)')], default='remote', max_length=20, verbose_name='Çalışma Modeli')),
                ('location', models.CharField(blank=True, help_text="Örn: İstanbul, Berlin veya 'Dünya Geneli'", max_length=120, verbose_name='Lokasyon / Şehir')),
                ('job_type', models.CharField(choices=[('full_time', 'Tam Zamanlı'), ('part_time', 'Yarı Zamanlı'), ('contract', 'Sözleşmeli / Freelance'), ('internship', 'Stajyer')], default='full_time', max_length=20, verbose_name='İstihdam Türü')),
                ('description', models.TextField(help_text='Aranan nitelikler, sorumluluklar ve teklif edilen yan haklar.', verbose_name='İş ve Rol Tanımı')),
                ('salary_range', models.CharField(blank=True, help_text='Örn: 90.000 TL - 130.000 TL / Ay veya $4,000 - $6,000', max_length=100, verbose_name='Bütçe / Maaş Skalası')),
                ('apply_url', models.CharField(help_text='Örn: https://sirketiniz.com/kariyer veya mailto:hr@sirket.com', max_length=255, verbose_name='Başvuru Linki veya E-posta')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Son Başvuru Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='İlan Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to=settings.AUTH_USER_MODEL, verbose_name='İlan Sahibi')),
            ],
            options={
                'verbose_name': 'İş İlanı',
                'verbose_name_plural': 'İş İlanları',
                'ordering': ['-created_at'],
            },
        ),
    ]
